language: java
jdk:
  - openjdk15

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      oggen18@gmail.com
    on_success: never
    on_failure: always
env:
  global:
    - CODECOV_TOKEN="5994408d-590d-4448-8206-4684b4f50797"